export * from './tabs';
export * from './tabs-actions';
export * from './tab';
export * from './tab-content';
export * from './tab-overflow-content';
export * from './tab-link.directive';
export * from './tab-action.directive';
export * from './tabs.module';
export { ClrTabsActionsPosition } from './tabs-actions';
export { TabsWillyWonka as ÇlrTabsWillyWonka } from './chocolate/tabs-willy-wonka';
export { ActiveOompaLoompa as ÇlrActiveOompaLoompa } from './chocolate/active-oompa-loompa';
