version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    target-branch: 'next'
    schedule:
      interval: 'weekly'
    # Ignore major version bumps for all dependencies
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']

  - package-ecosystem: 'npm'
    directory: '/'
    target-branch: 'main'
    schedule:
      interval: 'weekly'
    # Ignore major version bumps for all dependencies
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
