version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    target-branch: 'next'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 20
    groups:
      dev-dependencies:
        dependency-type: 'development'
        update-types: ['minor', 'patch']
    # Ignore major version bumps for all dependencies
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']

  - package-ecosystem: 'npm'
    directory: '/'
    target-branch: 'main'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 20
    groups:
      dev-dependencies:
        dependency-type: 'development'
        update-types: ['minor', 'patch']
    # Ignore major version bumps for all dependencies
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
