/*
 * Copyright (c) 2016-2026 Broadcom. All Rights Reserved.
 * The term "Broadcom" refers to Broadcom Inc. and/or its subsidiaries.
 * This software is released under MIT license.
 * The full license information can be found in LICENSE in the root directory of this project.
 */

import { HttpClient } from '@angular/common/http';
import { inject, Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { catchError, shareReplay } from 'rxjs/operators';

import { SearchIndexEntry } from './search-index.model';

// search-index.json is only generated by the CI Playwright crawl (projects/website/scripts/
// generate-sitemap.js) that runs after a production build, so it never exists during local
// `ng serve`/`ng build`. Missing/failed requests resolve to an empty index rather than erroring,
// so the search box degrades to "no results" locally instead of breaking.
@Injectable({ providedIn: 'root' })
export class SearchIndexService {
  private readonly httpClient = inject(HttpClient);

  private readonly index$: Observable<SearchIndexEntry[]> = this.httpClient
    .get<SearchIndexEntry[]>('/search-index.json')
    .pipe(
      catchError(() => of([])),
      shareReplay(1)
    );

  getIndex(): Observable<SearchIndexEntry[]> {
    return this.index$;
  }
}
