/*
 * Copyright (c) 2016-2025 Broadcom. All Rights Reserved.
 * The term "Broadcom" refers to Broadcom Inc. and/or its subsidiaries.
 * This software is released under MIT license.
 * The full license information can be found in LICENSE in the root directory of this project.
 */

export * from './utils/icon-html.pipe';
export * from './icon.module';
export * from './icon.component';
export * from './icon.service';
export * from './interfaces/icon.interfaces';
export { renderIcon } from './icon.renderer';

// SHAPES
export { unknownIcon, unknownIconName } from './shapes/unknown';

// SHAPES - CORE
export { angleIcon, angleIconName } from './shapes/angle';
export { angleDoubleIcon, angleDoubleIconName } from './shapes/angle-double';
export { arrowIcon, arrowIconName } from './shapes/arrow';
export { barsIcon, barsIconName } from './shapes/bars';
export { bellIcon, bellIconName } from './shapes/bell';
export { calendarIcon, calendarIconName } from './shapes/calendar';
export { checkIcon, checkIconName } from './shapes/check';
export { checkCircleIcon, checkCircleIconName } from './shapes/check-circle';
export { cloudIcon, cloudIconName } from './shapes/cloud';
export { cogIcon, cogIconName } from './shapes/cog';
export { ellipsisHorizontalIcon, ellipsisHorizontalIconName } from './shapes/ellipsis-horizontal';
export { ellipsisVerticalIcon, ellipsisVerticalIconName } from './shapes/ellipsis-vertical';
export { errorStandardIcon, errorStandardIconName } from './shapes/error-standard';
export { eventIcon, eventIconName } from './shapes/event';
export { exclamationCircleIcon, exclamationCircleIconName } from './shapes/exclamation-circle';
export { exclamationTriangleIcon, exclamationTriangleIconName } from './shapes/exclamation-triangle';
export { eyeIcon, eyeIconName } from './shapes/eye';
export { eyeHideIcon, eyeHideIconName } from './shapes/eye-hide';
export { filterGridIcon, filterGridIconName } from './shapes/filter-grid';
export { filterGridCircleIcon, filterGridCircleIconName } from './shapes/filter-grid-circle';
export { folderIcon, folderIconName } from './shapes/folder';
export { folderOpenIcon, folderOpenIconName } from './shapes/folder-open';
export { helpInfoIcon, helpInfoIconName } from './shapes/help-info';
export { homeIcon, homeIconName } from './shapes/home';
export { imageIcon, imageIconName } from './shapes/image';
export { infoCircleIcon, infoCircleIconName } from './shapes/info-circle';
export { infoStandardIcon, infoStandardIconName } from './shapes/info-standard';
export { searchIcon, searchIconName } from './shapes/search';
export { stepForward2Icon, stepForward2IconName } from './shapes/step-forward-2';
export { successStandardIcon, successStandardIconName } from './shapes/success-standard';
export { timesIcon, timesIconName } from './shapes/times';
export { unknownStatusIcon, unknownStatusIconName } from './shapes/unknown-status';
export { userIcon, userIconName } from './shapes/user';
export { viewColumnsIcon, viewColumnsIconName } from './shapes/view-columns';
export { vmBugIcon, vmBugIconName } from './shapes/vm-bug';
export { vmBugInverseIcon, vmBugInverseIconName } from './shapes/vm-bug-inverse';
export { warningStandardIcon, warningStandardIconName } from './shapes/warning-standard';
export { detailExpandIcon, detailExpandIconName } from './shapes/detail-expand';
export { detailCollapseIcon, detailCollapseIconName } from './shapes/detail-collapse';

// SHAPES - ESSENTIAL
export { accessibility1Icon, accessibility1IconName } from './shapes/accessibility-1';
export { accessibility2Icon, accessibility2IconName } from './shapes/accessibility-2';
export { announcementIcon, announcementIconName } from './shapes/announcement';
export { addTextIcon, addTextIconName } from './shapes/add-text';
export { alarmClockIcon, alarmClockIconName } from './shapes/alarm-clock';
export { alarmOffIcon, alarmOffIconName } from './shapes/alarm-off';
export { asteriskIcon, asteriskIconName } from './shapes/asterisk';
export { banIcon, banIconName } from './shapes/ban';
export { betaIcon, betaIconName } from './shapes/beta';
export { birthdayCakeIcon, birthdayCakeIconName } from './shapes/birthday-cake';
export { boltIcon, boltIconName } from './shapes/bolt';
export { bookIcon, bookIconName } from './shapes/book';
export { briefcaseIcon, briefcaseIconName } from './shapes/briefcase';
export { bubbleExclamationIcon, bubbleExclamationIconName } from './shapes/bubble-exclamation';
export { bugIcon, bugIconName } from './shapes/bug';
export { bullseyeIcon, bullseyeIconName } from './shapes/bullseye';
export { childArrowIcon, childArrowIconName } from './shapes/child-arrow';
export { circleIcon, circleIconName } from './shapes/circle';
export { circleArrowIcon, circleArrowIconName } from './shapes/circle-arrow';
export { clipboardIcon, clipboardIconName } from './shapes/clipboard';
export { clockIcon, clockIconName } from './shapes/clock';
export { cloneIcon, cloneIconName } from './shapes/clone';
export { collapseCardIcon, collapseCardIconName } from './shapes/collapse-card';
export { colorPaletteIcon, colorPaletteIconName } from './shapes/color-palette';
export { colorPickerIcon, colorPickerIconName } from './shapes/color-picker';
export { copyIcon, copyIconName } from './shapes/copy';
export { copyToClipboardIcon, copyToClipboardIconName } from './shapes/copy-to-clipboard';
export { crosshairsIcon, crosshairsIconName } from './shapes/crosshairs';
export { cursorArrowIcon, cursorArrowIconName } from './shapes/cursor-arrow';
export { cursorHandIcon, cursorHandIconName } from './shapes/cursor-hand';
export { cursorHandClickIcon, cursorHandClickIconName } from './shapes/cursor-hand-click';
export { cursorHandGrabIcon, cursorHandGrabIconName } from './shapes/cursor-hand-grab';
export { cursorHandOpenIcon, cursorHandOpenIconName } from './shapes/cursor-hand-open';
export { cursorMoveIcon, cursorMoveIconName } from './shapes/cursor-move';
export { detailsIcon, detailsIconName } from './shapes/details';
export { dotCircleIcon, dotCircleIconName } from './shapes/dot-circle';
export { downloadIcon, downloadIconName } from './shapes/download';
export { dragHandleIcon, dragHandleIconName } from './shapes/drag-handle';
export { dragHandleCornerIcon, dragHandleCornerIconName } from './shapes/drag-handle-corner';
export { eraserIcon, eraserIconName } from './shapes/eraser';
export { expandCardIcon, expandCardIconName } from './shapes/expand-card';
export { fileIcon, fileIconName } from './shapes/file';
export { fileGroupIcon, fileGroupIconName } from './shapes/file-group';
export { fileSettingsIcon, fileSettingsIconName } from './shapes/file-settings';
export { fileZipIcon, fileZipIconName } from './shapes/file-zip';
export { filterIcon, filterIconName } from './shapes/filter';
export { filter2Icon, filter2IconName } from './shapes/filter-2';
export { filterOffIcon, filterOffIconName } from './shapes/filter-off';
export { firewallIcon, firewallIconName } from './shapes/firewall';
export { firstAidIcon, firstAidIconName } from './shapes/first-aid';
export { fishIcon, fishIconName } from './shapes/fish';
export { flameIcon, flameIconName } from './shapes/flame';
export { formIcon, formIconName } from './shapes/form';
export { fuelIcon, fuelIconName } from './shapes/fuel';
export { gavelIcon, gavelIconName } from './shapes/gavel';
export { gridViewIcon, gridViewIconName } from './shapes/grid-view';
export { helpIcon, helpIconName } from './shapes/help';
export { historyIcon, historyIconName } from './shapes/history';
export { hourglassIcon, hourglassIconName } from './shapes/hourglass';
export { idBadgeIcon, idBadgeIconName } from './shapes/id-badge';
export { keyIcon, keyIconName } from './shapes/key';
export { landscapeIcon, landscapeIconName } from './shapes/landscape';
export { launchpadIcon, launchpadIconName } from './shapes/launchpad';
export { libraryIcon, libraryIconName } from './shapes/library';
export { lightbulbIcon, lightbulbIconName } from './shapes/lightbulb';
export { listIcon, listIconName } from './shapes/list';
export { lockIcon, lockIconName } from './shapes/lock';
export { loginIcon, loginIconName } from './shapes/login';
export { logoutIcon, logoutIconName } from './shapes/logout';
export { minusIcon, minusIconName } from './shapes/minus';
export { minusCircleIcon, minusCircleIconName } from './shapes/minus-circle';
export { moonIcon, moonIconName } from './shapes/moon';
export { newIcon, newIconName } from './shapes/new';
export { noAccessIcon, noAccessIconName } from './shapes/no-access';
export { noteIcon, noteIconName } from './shapes/note';
export { objectsIcon, objectsIconName } from './shapes/objects';
export { organizationIcon, organizationIconName } from './shapes/organization';
export { paperclipIcon, paperclipIconName } from './shapes/paperclip';
export { pasteIcon, pasteIconName } from './shapes/paste';
export { pencilIcon, pencilIconName } from './shapes/pencil';
export { pinIcon, pinIconName } from './shapes/pin';
export { pinboardIcon, pinboardIconName } from './shapes/pinboard';
export { plusIcon, plusIconName } from './shapes/plus';
export { plusCircleIcon, plusCircleIconName } from './shapes/plus-circle';
export { popOutIcon, popOutIconName } from './shapes/pop-out';
export { portraitIcon, portraitIconName } from './shapes/portrait';
export { printerIcon, printerIconName } from './shapes/printer';
export { recycleIcon, recycleIconName } from './shapes/recycle';
export { redoIcon, redoIconName } from './shapes/redo';
export { refreshIcon, refreshIconName } from './shapes/refresh';
export { repeatIcon, repeatIconName } from './shapes/repeat';
export { resizeIcon, resizeIconName } from './shapes/resize';
export { scissorsIcon, scissorsIconName } from './shapes/scissors';
export { scrollIcon, scrollIconName } from './shapes/scroll';
export { shrinkIcon, shrinkIconName } from './shapes/shrink';
export { sliderIcon, sliderIconName } from './shapes/slider';
export { snowflakeIcon, snowflakeIconName } from './shapes/snowflake';
export { sortByIcon, sortByIconName } from './shapes/sort-by';
export { sunIcon, sunIconName } from './shapes/sun';
export { switchIcon, switchIconName } from './shapes/switch';
export { syncIcon, syncIconName } from './shapes/sync';
export { tableIcon, tableIconName } from './shapes/table';
export { tagIcon, tagIconName } from './shapes/tag';
export { tagsIcon, tagsIconName } from './shapes/tags';
export { targetIcon, targetIconName } from './shapes/target';
export { thermometerIcon, thermometerIconName } from './shapes/thermometer';
export { timelineIcon, timelineIconName } from './shapes/timeline';
export { timesCircleIcon, timesCircleIconName } from './shapes/times-circle';
export { toolsIcon, toolsIconName } from './shapes/tools';
export { trashIcon, trashIconName } from './shapes/trash';
export { treeIcon, treeIconName } from './shapes/tree';
export { treeViewIcon, treeViewIconName } from './shapes/tree-view';
export { twoWayArrowsIcon, twoWayArrowsIconName } from './shapes/two-way-arrows';
export { undoIcon, undoIconName } from './shapes/undo';
export { unpinIcon, unpinIconName } from './shapes/unpin';
export { unlockIcon, unlockIconName } from './shapes/unlock';
export { uploadIcon, uploadIconName } from './shapes/upload';
export { usersIcon, usersIconName } from './shapes/users';
export { viewCardsIcon, viewCardsIconName } from './shapes/view-cards';
export { viewListIcon, viewListIconName } from './shapes/view-list';
export { volumeIcon, volumeIconName } from './shapes/volume';
export { wandIcon, wandIconName } from './shapes/wand';
export { windowCloseIcon, windowCloseIconName } from './shapes/window-close';
export { windowMaxIcon, windowMaxIconName } from './shapes/window-max';
export { windowMinIcon, windowMinIconName } from './shapes/window-min';
export { windowRestoreIcon, windowRestoreIconName } from './shapes/window-restore';
export { worldIcon, worldIconName } from './shapes/world';
export { wrenchIcon, wrenchIconName } from './shapes/wrench';
export { zoomInIcon, zoomInIconName } from './shapes/zoom-in';
export { zoomOutIcon, zoomOutIconName } from './shapes/zoom-out';

// SHAPES - CHARTS
export { axisChartIcon, axisChartIconName } from './shapes/axis-chart';
export { barChartIcon, barChartIconName } from './shapes/bar-chart';
export { bellCurveIcon, bellCurveIconName } from './shapes/bell-curve';
export { boxPlotIcon, boxPlotIconName } from './shapes/box-plot';
export { bubbleChartIcon, bubbleChartIconName } from './shapes/bubble-chart';
export { cloudChartIcon, cloudChartIconName } from './shapes/cloud-chart';
export { curveChartIcon, curveChartIconName } from './shapes/curve-chart';
export { gridChartIcon, gridChartIconName } from './shapes/grid-chart';
export { heatMapIcon, heatMapIconName } from './shapes/heat-map';
export { lineChartIcon, lineChartIconName } from './shapes/line-chart';
export { pieChartIcon, pieChartIconName } from './shapes/pie-chart';
export { scatterPlotIcon, scatterPlotIconName } from './shapes/scatter-plot';
export { tickChartIcon, tickChartIconName } from './shapes/tick-chart';

// SHAPES - COMMERCE
export { bankIcon, bankIconName } from './shapes/bank';
export { bitcoinIcon, bitcoinIconName } from './shapes/bitcoin';
export { calculatorIcon, calculatorIconName } from './shapes/calculator';
export { coinBagIcon, coinBagIconName } from './shapes/coin-bag';
export { creditCardIcon, creditCardIconName } from './shapes/credit-card';
export { dollarIcon, dollarIconName } from './shapes/dollar';
export { dollarBillIcon, dollarBillIconName } from './shapes/dollar-bill';
export { eCheckIcon, eCheckIconName } from './shapes/e-check';
export { employeeIcon, employeeIconName } from './shapes/employee';
export { employeeGroupIcon, employeeGroupIconName } from './shapes/employee-group';
export { euroIcon, euroIconName } from './shapes/euro';
export { factoryIcon, factoryIconName } from './shapes/factory';
export { pesoIcon, pesoIconName } from './shapes/peso';
export { piggyBankIcon, piggyBankIconName } from './shapes/piggy-bank';
export { poundIcon, poundIconName } from './shapes/pound';
export { rubleIcon, rubleIconName } from './shapes/ruble';
export { rupeeIcon, rupeeIconName } from './shapes/rupee';
export { shoppingBagIcon, shoppingBagIconName } from './shapes/shopping-bag';
export { shoppingCartIcon, shoppingCartIconName } from './shapes/shopping-cart';
export { storeIcon, storeIconName } from './shapes/store';
export { walletIcon, walletIconName } from './shapes/wallet';
export { wonIcon, wonIconName } from './shapes/won';
export { yenIcon, yenIconName } from './shapes/yen';

// SHAPES - MEDIA
export { cameraIcon, cameraIconName } from './shapes/camera';
export { fastForwardIcon, fastForwardIconName } from './shapes/fast-forward';
export { filmStripIcon, filmStripIconName } from './shapes/film-strip';
export { headphonesIcon, headphonesIconName } from './shapes/headphones';
export { imageGalleryIcon, imageGalleryIconName } from './shapes/image-gallery';
export { microphoneIcon, microphoneIconName } from './shapes/microphone';
export { microphoneMuteIcon, microphoneMuteIconName } from './shapes/microphone-mute';
export { musicNoteIcon, musicNoteIconName } from './shapes/music-note';
export { pauseIcon, pauseIconName } from './shapes/pause';
export { playIcon, playIconName } from './shapes/play';
export { powerIcon, powerIconName } from './shapes/power';
export { replayAllIcon, replayAllIconName } from './shapes/replay-all';
export { replayOneIcon, replayOneIconName } from './shapes/replay-one';
export { rewindIcon, rewindIconName } from './shapes/rewind';
export { shuffleIcon, shuffleIconName } from './shapes/shuffle';
export { stepForwardIcon, stepForwardIconName } from './shapes/step-forward';
export { stopIcon, stopIconName } from './shapes/stop';
export { videoCameraIcon, videoCameraIconName } from './shapes/video-camera';
export { videoGalleryIcon, videoGalleryIconName } from './shapes/video-gallery';
export { volumeDownIcon, volumeDownIconName } from './shapes/volume-down';
export { volumeMuteIcon, volumeMuteIconName } from './shapes/volume-mute';
export { volumeUpIcon, volumeUpIconName } from './shapes/volume-up';

// SHAPES - MINI
export { arrowMiniIcon, arrowMiniIconName } from './shapes/arrow-mini';
export { calendarMiniIcon, calendarMiniIconName } from './shapes/calendar-mini';
export { checkCircleMiniIcon, checkCircleMiniIconName } from './shapes/check-circle-mini';
export { checkMiniIcon, checkMiniIconName } from './shapes/check-mini';
export { errorMiniIcon, errorMiniIconName } from './shapes/error-mini';
export { eventMiniIcon, eventMiniIconName } from './shapes/event-mini';
export { filterGridCircleMiniIcon, filterGridCircleMiniIconName } from './shapes/filter-grid-circle-mini';
export { filterGridMiniIcon, filterGridMiniIconName } from './shapes/filter-grid-mini';
export { infoCircleMiniIcon, infoCircleMiniIconName } from './shapes/info-circle-mini';
export { timesMiniIcon, timesMiniIconName } from './shapes/times-mini';
export { warningMiniIcon, warningMiniIconName } from './shapes/warning-mini';

// SHAPES - TECHNOLOGY
export { administratorIcon, administratorIconName } from './shapes/administrator';
export { animationIcon, animationIconName } from './shapes/animation';
export { applicationIcon, applicationIconName } from './shapes/application';
export { applicationsIcon, applicationsIconName } from './shapes/applications';
export { archiveIcon, archiveIconName } from './shapes/archive';
export { assignUserIcon, assignUserIconName } from './shapes/assign-user';
export { atomIcon, atomIconName } from './shapes/atom';
export { backupIcon, backupIconName } from './shapes/backup';
export { backupRestoreIcon, backupRestoreIconName } from './shapes/backup-restore';
export { barCodeIcon, barCodeIconName } from './shapes/bar-code';
export { batteryIcon, batteryIconName } from './shapes/battery';
export { blockIcon, blockIconName } from './shapes/block';
export { blocksGroupIcon, blocksGroupIconName } from './shapes/blocks-group';
export { bluetoothIcon, bluetoothIconName } from './shapes/bluetooth';
export { bluetoothOffIcon, bluetoothOffIconName } from './shapes/bluetooth-off';
export { buildingIcon, buildingIconName } from './shapes/building';
export { bundleIcon, bundleIconName } from './shapes/bundle';
export { capacitorIcon, capacitorIconName } from './shapes/capacitor';
export { cdDvdIcon, cdDvdIconName } from './shapes/cd-dvd';
export { certificateIcon, certificateIconName } from './shapes/certificate';
export { ciCdIcon, ciCdIconName } from './shapes/ci-cd';
export { cloudNetworkIcon, cloudNetworkIconName } from './shapes/cloud-network';
export { cloudScaleIcon, cloudScaleIconName } from './shapes/cloud-scale';
export { cloudTrafficIcon, cloudTrafficIconName } from './shapes/cloud-traffic';
export { clusterIcon, clusterIconName } from './shapes/cluster';
export { codeIcon, codeIconName } from './shapes/code';
export { computerIcon, computerIconName } from './shapes/computer';
export { connectIcon, connectIconName } from './shapes/connect';
export { containerIcon, containerIconName } from './shapes/container';
export { containerGroupIcon, containerGroupIconName } from './shapes/container-group';
export { containerVolumeIcon, containerVolumeIconName } from './shapes/container-volume';
export { controlLunIcon, controlLunIconName } from './shapes/control-lun';
export { cpuIcon, cpuIconName } from './shapes/cpu';
export { dashboardIcon, dashboardIconName } from './shapes/dashboard';
export { dataClusterIcon, dataClusterIconName } from './shapes/data-cluster';
export { deployIcon, deployIconName } from './shapes/deploy';
export { devicesIcon, devicesIconName } from './shapes/devices';
export { digitalSignatureIcon, digitalSignatureIconName } from './shapes/digital-signature';
export { disconnectIcon, disconnectIconName } from './shapes/disconnect';
export { displayIcon, displayIconName } from './shapes/display';
export { downloadCloudIcon, downloadCloudIconName } from './shapes/download-cloud';
export { exportIcon, exportIconName } from './shapes/export';
export { fileShare2Icon, fileShare2IconName } from './shapes/file-share-2';
export { fileShareIcon, fileShareIconName } from './shapes/file-share';
export { flaskIcon, flaskIconName } from './shapes/flask';
export { floppyIcon, floppyIconName } from './shapes/floppy';
export { forkingIcon, forkingIconName } from './shapes/forking';
export { hardDiskIcon, hardDiskIconName } from './shapes/hard-disk';
export { hardDriveDisksIcon, hardDriveDisksIconName } from './shapes/hard-drive-disks';
export { hardDriveIcon, hardDriveIconName } from './shapes/hard-drive';
export { helixIcon, helixIconName } from './shapes/helix';
export { hostGroupIcon, hostGroupIconName } from './shapes/host-group';
export { hostIcon, hostIconName } from './shapes/host';
export { importIcon, importIconName } from './shapes/import';
export { inductorIcon, inductorIconName } from './shapes/inductor';
export { installIcon, installIconName } from './shapes/install';
export { internetOfThingsIcon, internetOfThingsIconName } from './shapes/internet-of-things';
export { keyboardIcon, keyboardIconName } from './shapes/keyboard';
export { layersIcon, layersIconName } from './shapes/layers';
export { linkIcon, linkIconName } from './shapes/link';
export { mediaChangerIcon, mediaChangerIconName } from './shapes/media-changer';
export { memoryIcon, memoryIconName } from './shapes/memory';
export { mobileIcon, mobileIconName } from './shapes/mobile';
export { mouseIcon, mouseIconName } from './shapes/mouse';
export { namespaceIcon, namespaceIconName } from './shapes/namespace';
export { networkGlobeIcon, networkGlobeIconName } from './shapes/network-globe';
export { networkSettingsIcon, networkSettingsIconName } from './shapes/network-settings';
export { networkSwitchIcon, networkSwitchIconName } from './shapes/network-switch';
export { nodeGroupIcon, nodeGroupIconName } from './shapes/node-group';
export { nodeIcon, nodeIconName } from './shapes/node';
export { nodesIcon, nodesIconName } from './shapes/nodes';
export { noWifiIcon, noWifiIconName } from './shapes/no-wifi';
export { nvmeIcon, nvmeIconName } from './shapes/nvme';
export { pdfFileIcon, pdfFileIconName } from './shapes/pdf-file';
export { phoneHandsetIcon, phoneHandsetIconName } from './shapes/phone-handset';
export { pluginIcon, pluginIconName } from './shapes/plugin';
export { podIcon, podIconName } from './shapes/pod';
export { processOnVmIcon, processOnVmIconName } from './shapes/process-on-vm';
export { qrCodeIcon, qrCodeIconName } from './shapes/qr-code';
export { rackServerIcon, rackServerIconName } from './shapes/rack-server';
export { radarIcon, radarIconName } from './shapes/radar';
export { resistorIcon, resistorIconName } from './shapes/resistor';
export { resourcePoolIcon, resourcePoolIconName } from './shapes/resource-pool';
export { routerIcon, routerIconName } from './shapes/router';
export { rulerPencilIcon, rulerPencilIconName } from './shapes/ruler-pencil';
export { scriptExecuteIcon, scriptExecuteIconName } from './shapes/script-execute';
export { scriptScheduleIcon, scriptScheduleIconName } from './shapes/script-schedule';
export { shieldCheckIcon, shieldCheckIconName } from './shapes/shield-check';
export { shieldIcon, shieldIconName } from './shapes/shield';
export { shieldXIcon, shieldXIconName } from './shapes/shield-x';
export { squidIcon, squidIconName } from './shapes/squid';
export { ssdIcon, ssdIconName } from './shapes/ssd';
export { storageAdapterIcon, storageAdapterIconName } from './shapes/storage-adapter';
export { storageIcon, storageIconName } from './shapes/storage';
export { tabletIcon, tabletIconName } from './shapes/tablet';
export { tapeDriveIcon, tapeDriveIconName } from './shapes/tape-drive';
export { terminalIcon, terminalIconName } from './shapes/terminal';
export { thinClientIcon, thinClientIconName } from './shapes/thin-client';
export { unarchiveIcon, unarchiveIconName } from './shapes/unarchive';
export { uninstallIcon, uninstallIconName } from './shapes/uninstall';
export { unlinkIcon, unlinkIconName } from './shapes/unlink';
export { updateIcon, updateIconName } from './shapes/update';
export { uploadCloudIcon, uploadCloudIconName } from './shapes/upload-cloud';
export { usbIcon, usbIconName } from './shapes/usb';
export { vmIcon, vmIconName } from './shapes/vm';
export { vmwAppIcon, vmwAppIconName } from './shapes/vmw-app';
export { wifiIcon, wifiIconName } from './shapes/wifi';
export { xlsFileIcon, xlsFileIconName } from './shapes/xls-file';

// SHAPES - SOCIAL
export { bookmarkIcon, bookmarkIconName } from './shapes/bookmark';
export { chatBubbleIcon, chatBubbleIconName } from './shapes/chat-bubble';
export { contractIcon, contractIconName } from './shapes/contract';
export { crownIcon, crownIconName } from './shapes/crown';
export { envelopeIcon, envelopeIconName } from './shapes/envelope';
export { flagIcon, flagIconName } from './shapes/flag';
export { halfStarIcon, halfStarIconName } from './shapes/half-star';
export { happyFaceIcon, happyFaceIconName } from './shapes/happy-face';
export { hashtagIcon, hashtagIconName } from './shapes/hashtag';
export { heartIcon, heartIconName } from './shapes/heart';
export { heartBrokenIcon, heartBrokenIconName } from './shapes/heart-broken';
export { inboxIcon, inboxIconName } from './shapes/inbox';
export { neutralFaceIcon, neutralFaceIconName } from './shapes/neutral-face';
export { pictureIcon, pictureIconName } from './shapes/picture';
export { sadFaceIcon, sadFaceIconName } from './shapes/sad-face';
export { shareIcon, shareIconName } from './shapes/share';
export { starIcon, starIconName } from './shapes/star';
export { talkBubblesIcon, talkBubblesIconName } from './shapes/talk-bubbles';
export { tasksIcon, tasksIconName } from './shapes/tasks';
export { thumbsDownIcon, thumbsDownIconName } from './shapes/thumbs-down';
export { thumbsUpIcon, thumbsUpIconName } from './shapes/thumbs-up';

// SHAPES - TEXT-EDIT
export { alignBottomIcon, alignBottomIconName } from './shapes/align-bottom';
export { alignCenterIcon, alignCenterIconName } from './shapes/align-center';
export { alignLeftIcon, alignLeftIconName } from './shapes/align-left';
export { alignLeftTextIcon, alignLeftTextIconName } from './shapes/align-left-text';
export { alignMiddleIcon, alignMiddleIconName } from './shapes/align-middle';
export { alignRightIcon, alignRightIconName } from './shapes/align-right';
export { alignRightTextIcon, alignRightTextIconName } from './shapes/align-right-text';
export { alignTopIcon, alignTopIconName } from './shapes/align-top';
export { blockQuoteIcon, blockQuoteIconName } from './shapes/block-quote';
export { boldIcon, boldIconName } from './shapes/bold';
export { bulletListIcon, bulletListIconName } from './shapes/bullet-list';
export { centerTextIcon, centerTextIconName } from './shapes/center-text';
export { checkboxListIcon, checkboxListIconName } from './shapes/checkbox-list';
export { fontSizeIcon, fontSizeIconName } from './shapes/font-size';
export { highlighterIcon, highlighterIconName } from './shapes/highlighter';
export { indentIcon, indentIconName } from './shapes/indent';
export { italicIcon, italicIconName } from './shapes/italic';
export { justifyTextIcon, justifyTextIconName } from './shapes/justify-text';
export { languageIcon, languageIconName } from './shapes/language';
export { numberListIcon, numberListIconName } from './shapes/number-list';
export { outdentIcon, outdentIconName } from './shapes/outdent';
export { paintRollerIcon, paintRollerIconName } from './shapes/paint-roller';
export { strikethroughIcon, strikethroughIconName } from './shapes/strikethrough';
export { subscriptIcon, subscriptIconName } from './shapes/subscript';
export { superscriptIcon, superscriptIconName } from './shapes/superscript';
export { textIcon, textIconName } from './shapes/text';
export { textColorIcon, textColorIconName } from './shapes/text-color';
export { underlineIcon, underlineIconName } from './shapes/underline';

// SHAPES - TRAVEL
export { airplaneIcon, airplaneIconName } from './shapes/airplane';
export { bicycleIcon, bicycleIconName } from './shapes/bicycle';
export { boatIcon, boatIconName } from './shapes/boat';
export { campervanIcon, campervanIconName } from './shapes/campervan';
export { carIcon, carIconName } from './shapes/car';
export { caravanIcon, caravanIconName } from './shapes/caravan';
export { compassIcon, compassIconName } from './shapes/compass';
export { ferryIcon, ferryIconName } from './shapes/ferry';
export { mapIcon, mapIconName } from './shapes/map';
export { mapMarkerIcon, mapMarkerIconName } from './shapes/map-marker';
export { onHolidayIcon, onHolidayIconName } from './shapes/on-holiday';
export { trailerIcon, trailerIconName } from './shapes/trailer';
export { truckIcon, truckIconName } from './shapes/truck';

// COLLECTIONS
export { loadChartIconSet, chartCollectionIcons, chartCollectionAliases } from './collections/chart';
export { loadCommerceIconSet, commerceCollectionIcons, commerceCollectionAliases } from './collections/commerce';
export { loadCoreIconSet, coreCollectionIcons, coreCollectionAliases } from './collections/core';
export { loadEssentialIconSet, essentialCollectionIcons, essentialCollectionAliases } from './collections/essential';
export { loadMediaIconSet, mediaCollectionIcons, mediaCollectionAliases } from './collections/media';
export { loadMiniIconSet, miniCollectionIcons, miniCollectionAliases } from './collections/mini';
export {
  loadTechnologyIconSet,
  technologyCollectionIcons,
  technologyCollectionAliases,
} from './collections/technology';
export { loadSocialIconSet, socialCollectionIcons, socialCollectionAliases } from './collections/social';
export { loadTextEditIconSet, textEditCollectionIcons, textEditCollectionAliases } from './collections/text-edit';
export { loadTravelIconSet, travelCollectionIcons, travelCollectionAliases } from './collections/travel';
