/*
 * Copyright (c) 2016-2026 Broadcom. All Rights Reserved.
 * The term "Broadcom" refers to Broadcom Inc. and/or its subsidiaries.
 * This software is released under MIT license.
 * The full license information can be found in LICENSE in the root directory of this project.
 */

import {
  ClrIcon,
  ClrMainContainerModule,
  ClrNavigationModule,
  ClrWizard,
  ClrWizardModule,
  commonStringsDefault,
} from '@clr/angular';
import { type Meta, moduleMetadata, type StoryObj } from '@storybook/angular';
import { hideControls } from '@storybook-helpers/arg-types';
import { withStyles } from '@storybook-helpers/decorators';
import { action } from 'storybook/actions';

/**
 * `ClrWizard` aliases every input and output (`@Input('clrWizardInPage') inPage`), so the class cannot
 * be the args type -- none of the `clrWizard*` names the template binds are properties of it. The args
 * are declared standalone, with the methods picked from `ClrWizard` so the `argTypes` entries that hide
 * them from the table generated by `component: ClrWizard` stay type-checked.
 */
type WizardInPageArgs = Pick<
  ClrWizard,
  | 'cancel'
  | 'checkAndCancel'
  | 'close'
  | 'finish'
  | 'forceFinish'
  | 'forceNext'
  | 'goTo'
  | 'next'
  | 'open'
  | 'previous'
  | 'reset'
  | 'toggle'
> & {
  // inputs
  clrHeadingLevel: number;
  clrWizardDisableStepnav: boolean;
  clrWizardPreventNavigation: boolean;
  clrWizardForceForwardNavigation: boolean;
  clrWizardPreventDefaultNext: boolean;
  clrWizardPreventDefaultCancel: boolean;
  clrWizardInPageFillContentArea: boolean;
  clrWizardStepnavAriaLabel: string;
  // outputs
  clrWizardCurrentPageChange: (event: unknown) => void;
  clrWizardOnNext: (event: unknown) => void;
  clrWizardOnPrevious: (event: unknown) => void;
  clrWizardOnCancel: (event: unknown) => void;
  clrWizardOnFinish: (event: unknown) => void;
  clrWizardOnReset: (event: unknown) => void;
  // story helpers
  createArray: (n: number) => unknown[];
  pageCount: number;
};

/**
 * Was an inline style block at the head of the story template; `withStyles()` injects it
 * unencapsulated, exactly as the inline block did.
 */
const IN_PAGE_WIZARD_STYLES = `
  ::ng-deep body.sb-main-padded.sb-main-padded {
    padding: 0;
  }
`;

const meta: Meta<WizardInPageArgs> = {
  title: 'Wizard/Wizard (in-page)',
  component: ClrWizard,
  decorators: [
    moduleMetadata({
      imports: [ClrMainContainerModule, ClrNavigationModule, ClrWizardModule, ClrIcon],
    }),
    withStyles(IN_PAGE_WIZARD_STYLES),
  ],
  argTypes: {
    // inputs
    clrHeadingLevel: { control: { type: 'number', min: 1, max: 6 } },
    // hidden inputs (these are not relevant to this story)
    ...hideControls(
      'clrWizardOpen',
      'clrWizardClosable',
      'clrWizardSize',
      'clrWizardInPage',
      'clrWizardPreventModalAnimation'
    ),
    // outputs
    clrWizardCurrentPageChange: { control: { disable: true } },
    clrWizardOnNext: { control: { disable: true } },
    clrWizardOnPrevious: { control: { disable: true } },
    clrWizardOnCancel: { control: { disable: true } },
    clrWizardOnFinish: { control: { disable: true } },
    clrWizardOnReset: { control: { disable: true } },
    // hidden outputs (these are not relevant to this story)
    ...hideControls('clrWizardOpenChange'),
    // methods
    cancel: { control: { disable: true } },
    checkAndCancel: { control: { disable: true } },
    close: { control: { disable: true } },
    finish: { control: { disable: true } },
    forceFinish: { control: { disable: true } },
    forceNext: { control: { disable: true } },
    goTo: { control: { disable: true } },
    ...hideControls('modalCancel'),
    next: { control: { disable: true } },
    open: { control: { disable: true } },
    previous: { control: { disable: true } },
    reset: { control: { disable: true } },
    toggle: { control: { disable: true } },
    // story helpers
    ...hideControls('createArray'),
    pageCount: { control: { type: 'number', min: 1, max: 100 } },
  },
  args: {
    // inputs
    clrHeadingLevel: 1,
    clrWizardDisableStepnav: false,
    clrWizardPreventNavigation: false,
    clrWizardForceForwardNavigation: false,
    clrWizardPreventDefaultNext: false,
    clrWizardPreventDefaultCancel: false,
    clrWizardInPageFillContentArea: false,
    clrWizardStepnavAriaLabel: commonStringsDefault.wizardStepnavAriaLabel,
    // outputs
    clrWizardCurrentPageChange: action('clrWizardCurrentPageChange'),
    clrWizardOnNext: action('clrWizardOnNext'),
    clrWizardOnPrevious: action('clrWizardOnPrevious'),
    clrWizardOnCancel: function (...args) {
      action('clrWizardOnCancel').apply(this, args);
      alert(
        'The application should handle cancelling an in-page wizard by navigating to a different page or taking some other appropriate action.'
      );
    },
    clrWizardOnFinish: function (...args) {
      action('clrWizardOnFinish').apply(this, args);
      alert(
        'The application should handle submitting an in-page wizard by navigating to a different page or taking some other appropriate action.'
      );
    },
    clrWizardOnReset: action('clrWizardOnFinish'),
    // story helpers
    createArray: n => new Array(n),
    pageCount: 4,
  },
  parameters: {
    docs: {
      story: {
        inline: false,
        height: 500,
      },
    },
  },
  render: args => ({
    template: `
      <clr-main-container>
        <clr-header>
          <div class="branding">
            <a href="javascript://" class="nav-link">
              <cds-icon shape="vm-bug"></cds-icon>
              <span class="title">Page Header</span>
            </a>
          </div>
        </clr-header>
        <div class="content-container">
          <div class="content-area">
            <clr-wizard
              [clrWizardInPage]="true"
              [clrWizardInPageFillContentArea]="clrWizardInPageFillContentArea"
              [clrWizardClosable]="false"
              [clrWizardDisableStepnav]="clrWizardDisableStepnav"
              [clrWizardPreventNavigation]="clrWizardPreventNavigation"
              [clrWizardForceForwardNavigation]="clrWizardForceForwardNavigation"
              [clrWizardPreventDefaultNext]="clrWizardPreventDefaultNext"
              [clrWizardPreventDefaultCancel]="clrWizardPreventDefaultCancel"
              [clrWizardStepnavAriaLabel]="clrWizardStepnavAriaLabel"
              (clrWizardCurrentPageChange)="clrWizardCurrentPageChange($event)"
              (clrWizardOnNext)="clrWizardOnNext($event)"
              (clrWizardOnPrevious)="clrWizardOnPrevious($event)"
              (clrWizardOnCancel)="clrWizardOnCancel($event)"
              (clrWizardOnFinish)="clrWizardOnFinish($event)"
              (clrWizardOnReset)="clrWizardOnReset($event)"
            >
              <clr-wizard-title [clrHeadingLevel]="clrHeadingLevel">Wizard</clr-wizard-title>

              <clr-wizard-button type="cancel">Cancel</clr-wizard-button>
              <clr-wizard-button type="previous">Previous</clr-wizard-button>
              <clr-wizard-button type="next">Next</clr-wizard-button>
              <clr-wizard-button type="finish">Finish</clr-wizard-button>

              @for (_ of createArray(pageCount); track $index; let i = $index) {
                <clr-wizard-page>
                  <ng-template clrPageTitle>Page {{ i + 1 }}</ng-template>
                  <p>Content for page {{ i + 1 }}.</p>
                </clr-wizard-page>
              }
            </clr-wizard>
          </div>
        </div>
      </clr-main-container>
    `,
    props: { ...args },
  }),
};

export default meta;

type Story = StoryObj<WizardInPageArgs>;

export const InPageWizard: Story = {};

export const InPageWizardFillContentArea: Story = {
  args: {
    clrWizardInPageFillContentArea: true,
  },
};
