/*
 * Copyright (c) 2016-2026 Broadcom. All Rights Reserved.
 * The term "Broadcom" refers to Broadcom Inc. and/or its subsidiaries.
 * This software is released under MIT license.
 * The full license information can be found in LICENSE in the root directory of this project.
 */

import { CommonModule } from '@angular/common';
import { AfterViewInit, Component, ElementRef, OnDestroy, OnInit, ViewChild } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ClarityIcons, ClarityModule, pencilIcon, undoIcon } from '@clr/angular';

import { Color, hexToHsl, hslToHex, shiftL } from './utils/color';
import { buildCssBlock } from './utils/css-generation';
import { cloneThemeColors, PRESETS, SAMPLE_ROWS, TOKEN_KEYS } from './utils/presets';
import { buildDerivedSet } from './utils/theme-derivation';
import { DataRow, DerivableField, DerivedSet, HslColor, ThemeColors, ThemePreset } from './utils/types';
import { contrastRatio, wcagScore } from './utils/wcag';
import { CodeSnippetComponent } from '../shared/code-snippet/code-snippet.component';
import { SiteFooterComponent } from '../shared/site-footer/site-footer.component';
import { SiteNavComponent } from '../shared/site-nav/site-nav.component';

export type { DataRow, DerivableField, DerivedSet, ThemeColors, ThemePreset };

@Component({
  selector: 'app-theme-builder',
  templateUrl: './theme-builder.component.html',
  styleUrl: './theme-builder.component.scss',
  host: { '[class.content-container]': 'true' },
  imports: [CommonModule, ClarityModule, FormsModule, CodeSnippetComponent, SiteFooterComponent, SiteNavComponent],
})
export class ThemeBuilderComponent implements OnInit, AfterViewInit, OnDestroy {
  @ViewChild('previewWrapper') previewWrapper!: ElementRef<HTMLElement>;

  presets = PRESETS;
  activeTheme: 'light' | 'dark' = 'light';
  outputTab: 'light' | 'dark' | 'combined' = 'combined';

  // Tracks which preset is active so CSS output can use token refs instead of hex values.
  // Set to null when the user manually edits any color.
  activePreset: ThemePreset | null = PRESETS[0];

  colors: { light: ThemeColors; dark: ThemeColors } = {
    light: cloneThemeColors(PRESETS[0].light),
    dark: cloneThemeColors(PRESETS[0].dark),
  };

  derived: { light: DerivedSet; dark: DerivedSet } = {
    light: buildDerivedSet(PRESETS[0].light, null, false),
    dark: buildDerivedSet(PRESETS[0].dark, null, true),
  };

  colorStruct: { light: {}; dark: {} } = {
    light: null,
    dark: null,
  };

  wizardOpen = false;
  rows = SAMPLE_ROWS;

  copied = false;
  private copiedTimer: ReturnType<typeof setTimeout> | null = null;

  constructor() {
    ClarityIcons.addIcons(undoIcon);
    ClarityIcons.addIcons(pencilIcon);
  }

  get current(): ThemeColors {
    return this.colors[this.activeTheme];
  }

  get currentDerived(): DerivedSet {
    return this.derived[this.activeTheme];
  }

  get isDarkTheme(): boolean {
    return this.activeTheme === 'dark';
  }

  get primaryContrastOnWhite(): number {
    return contrastRatio(this.current.primary.rgb, [255, 255, 255]);
  }

  get primaryContrastOnBlack(): number {
    return contrastRatio(this.current.primary.rgb, [0, 0, 0]);
  }

  get primaryScoreOnWhite(): string {
    return wcagScore(this.primaryContrastOnWhite);
  }

  get primaryScoreOnBlack(): string {
    return wcagScore(this.primaryContrastOnBlack);
  }

  get textContrastOnContainer(): number {
    return contrastRatio(this.current.text.rgb, this.current.containerBg.rgb);
  }

  get textScoreOnContainer(): string {
    return wcagScore(this.textContrastOnContainer);
  }

  get generatedCss(): string {
    if (this.outputTab === 'light') {
      return buildCssBlock(this.colors.light, this.derived.light, 'light', this.activePreset?.lightCssTokens);
    }

    if (this.outputTab === 'dark') {
      return buildCssBlock(this.colors.dark, this.derived.dark, 'dark', this.activePreset?.darkCssTokens);
    }

    const light = buildCssBlock(this.colors.light, this.derived.light, 'light', this.activePreset?.lightCssTokens);
    const dark = buildCssBlock(this.colors.dark, this.derived.dark, 'dark', this.activePreset?.darkCssTokens);

    // const colorGroups = this.colorStruct[this.activeTheme];
    //
    // for (let colorGroupKey in colorGroups) {
    //   const colorVariants = colorGroups[colorGroupKey];
    //   for (let i = 0; i < colorVariants.length; i++) {
    //     const color = colorVariants[i] as Color;
    //     el.style.setProperty(color.name, color.hsl);
    //   }
    // }

    return `/* Clarity Theme Override — generated by Clarity Theme Builder */\n\n${light}\n\n${dark}`;
  }

  get themeColors() {
    if (this.colorStruct[this.activeTheme]) {
      return Object.keys(this.colorStruct[this.activeTheme]);
    }

    return [];
  }

  applyActiveTheme(theme: 'light' | 'dark') {
    this.activeTheme = theme;

    this.buildColorStructure();

    this.applyPreviewStyles();
  }

  colorToHex([h, s, l]: HslColor): string {
    return hslToHex(h, s, l);
  }

  colorToHsl([h, s, l]: HslColor): string {
    return `hsl(${h}, ${s}%, ${l}%)`;
  }

  setCurrentColor(colorVariant: Color, hex: string, colorGroup: Color[]): void {
    if (/^#[0-9a-fA-F]{6}$/.test(hex)) {
      colorVariant.color = hexToHsl(hex);
      // this.onColorChange();

      if (TOKEN_KEYS.baseTokens.includes(colorVariant.name)) {
        const baseColorHSL = colorVariant.color;

        colorGroup.forEach(item => {
          if (item.name.endsWith('-tint')) {
            item.color = [baseColorHSL[0], baseColorHSL[1], this.isDarkTheme ? 6 : 94];
          } else if (item.name.endsWith('-tint-dark')) {
            item.color = [baseColorHSL[0], baseColorHSL[1], this.isDarkTheme ? 5 : 95];
          } else if (item.name.endsWith('-shade')) {
            item.color = shiftL(baseColorHSL, this.isDarkTheme ? 7 : -7);
          } else if (item.name.endsWith('-dark')) {
            item.color = shiftL(baseColorHSL, this.isDarkTheme ? 10 : -10);
          }
        });

        console.log(colorGroup);
      }

      this.applyPreviewStyles();
    }
  }

  setDerivedOverride(field: DerivableField, hex: string): void {
    field.override = hexToHsl(hex);
    this.onDerivedChange();
  }

  ngOnInit(): void {
    console.log('ngOnInit');
    // document.querySelector('app-root')?.classList.add('layout-theme-builder');
  }

  ngAfterViewInit(): void {
    this.buildColorStructure();

    this.applyPreviewStyles();
  }

  ngOnDestroy(): void {
    console.log('ngOnDestroy');
    if (this.copiedTimer) {
      clearTimeout(this.copiedTimer);
    }
  }

  applyPreset(preset: ThemePreset): void {
    this.activePreset = preset;
    this.colors.light = cloneThemeColors(preset.light);
    this.colors.dark = cloneThemeColors(preset.dark);
    this.recomputeDerived();
  }

  onColorChange(): void {
    this.activePreset = null;
    this.recomputeDerived();
  }

  toggleManual(field: keyof DerivedSet): void {
    const f = this.currentDerived[field];
    if (!f.useManual) {
      f.override = f.auto;
    }
    f.useManual = !f.useManual;
    this.applyPreviewStyles();
  }

  onDerivedChange(): void {
    this.applyPreviewStyles();
  }

  async copyCSS(): Promise<void> {
    try {
      await navigator.clipboard.writeText(this.generatedCss);
      this.copied = true;
      if (this.copiedTimer) {
        clearTimeout(this.copiedTimer);
      }
      this.copiedTimer = setTimeout(() => (this.copied = false), 2000);
    } catch {
      // clipboard not available — silently ignore
    }
  }

  applyPreviewStyles(): void {
    const el = this.previewWrapper?.nativeElement;
    if (!el) {
      return;
    }

    const colorGroups = this.colorStruct[this.activeTheme];

    for (let colorGroupKey in colorGroups) {
      const colorVariants = colorGroups[colorGroupKey];
      for (let i = 0; i < colorVariants.length; i++) {
        const color = colorVariants[i] as Color;
        el.style.setProperty(color.name, color.hsl);
      }
    }
  }

  private buildColorStructure() {
    setTimeout(() => {
      if (this.colorStruct[this.activeTheme] !== null) {
        return;
      }

      const style = window.getComputedStyle(this.previewWrapper?.nativeElement);

      this.colorStruct[this.activeTheme] = {};

      for (const key in TOKEN_KEYS) {
        if (key === 'baseTokens') {
          continue;
        }

        const tokenGroup = TOKEN_KEYS[key];
        this.colorStruct[this.activeTheme][key] = [];
        for (let i = 0; i < tokenGroup.length; i++) {
          this.colorStruct[this.activeTheme][key].push(new Color(tokenGroup[i], style.getPropertyValue(tokenGroup[i])));
        }
      }

      console.log(this.colorStruct);
    }, 200);
  }

  private recomputeDerived(): void {
    this.derived.light = buildDerivedSet(this.colors.light, this.derived.light, false);
    this.derived.dark = buildDerivedSet(this.colors.dark, this.derived.dark, true);
    this.applyPreviewStyles();
  }
}
