/*
 * Copyright (c) 2016-2026 Broadcom. All Rights Reserved.
 * The term "Broadcom" refers to Broadcom Inc. and/or its subsidiaries.
 * This software is released under MIT license.
 * The full license information can be found in LICENSE in the root directory of this project.
 */

import { CommonModule } from '@angular/common';
import { AfterViewInit, Component, ElementRef, OnDestroy, OnInit, ViewChild } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ClarityIcons, ClarityModule, pencilIcon, undoIcon } from '@clr/angular';

import { hexToHsl, hslToHex } from './utils/color';
import { buildCssBlock } from './utils/css-generation';
import { cloneThemeColors, PRESETS, SAMPLE_ROWS } from './utils/presets';
import { buildDerivedSet, effectiveValue } from './utils/theme-derivation';
import { DataRow, DerivableField, DerivedSet, HslColor, ThemeColors, ThemePreset } from './utils/types';
import { contrastRatio, wcagScore } from './utils/wcag';
import { CodeSnippetComponent } from '../shared/code-snippet/code-snippet.component';
import { SiteFooterComponent } from '../shared/site-footer/site-footer.component';
import { SiteNavComponent } from '../shared/site-nav/site-nav.component';

export type { DataRow, DerivableField, DerivedSet, ThemeColors, ThemePreset };

@Component({
  selector: 'app-theme-builder',
  templateUrl: './theme-builder.component.html',
  styleUrl: './theme-builder.component.scss',
  host: { '[class.content-container]': 'true' },
  imports: [CommonModule, ClarityModule, FormsModule, CodeSnippetComponent, SiteFooterComponent, SiteNavComponent],
})
export class ThemeBuilderComponent implements OnInit, AfterViewInit, OnDestroy {
  @ViewChild('previewWrapper') previewWrapper!: ElementRef<HTMLElement>;

  presets = PRESETS;
  activeTheme: 'light' | 'dark' = 'light';
  outputTab: 'light' | 'dark' | 'combined' = 'combined';

  // Tracks which preset is active so CSS output can use token refs instead of hex values.
  // Set to null when the user manually edits any color.
  activePreset: ThemePreset | null = PRESETS[0];

  colors: { light: ThemeColors; dark: ThemeColors } = {
    light: cloneThemeColors(PRESETS[0].light),
    dark: cloneThemeColors(PRESETS[0].dark),
  };

  derived: { light: DerivedSet; dark: DerivedSet } = {
    light: buildDerivedSet(PRESETS[0].light, null, false),
    dark: buildDerivedSet(PRESETS[0].dark, null, true),
  };

  wizardOpen = false;
  rows = SAMPLE_ROWS;

  copied = false;
  private copiedTimer: ReturnType<typeof setTimeout> | null = null;

  constructor() {
    ClarityIcons.addIcons(undoIcon);
    ClarityIcons.addIcons(pencilIcon);
  }

  get current(): ThemeColors {
    return this.colors[this.activeTheme];
  }

  get currentDerived(): DerivedSet {
    return this.derived[this.activeTheme];
  }

  get isDarkTheme(): boolean {
    return this.activeTheme === 'dark';
  }

  get primaryContrastOnWhite(): number {
    return contrastRatio(this.current.primary.rgb, [255, 255, 255]);
  }

  get primaryContrastOnBlack(): number {
    return contrastRatio(this.current.primary.rgb, [0, 0, 0]);
  }

  get primaryScoreOnWhite(): string {
    return wcagScore(this.primaryContrastOnWhite);
  }

  get primaryScoreOnBlack(): string {
    return wcagScore(this.primaryContrastOnBlack);
  }

  get textContrastOnContainer(): number {
    return contrastRatio(this.current.text.rgb, this.current.containerBg.rgb);
  }

  get textScoreOnContainer(): string {
    return wcagScore(this.textContrastOnContainer);
  }

  get generatedCss(): string {
    if (this.outputTab === 'light') {
      return buildCssBlock(this.colors.light, this.derived.light, 'light', this.activePreset?.lightCssTokens);
    }

    if (this.outputTab === 'dark') {
      return buildCssBlock(this.colors.dark, this.derived.dark, 'dark', this.activePreset?.darkCssTokens);
    }

    const light = buildCssBlock(this.colors.light, this.derived.light, 'light', this.activePreset?.lightCssTokens);
    const dark = buildCssBlock(this.colors.dark, this.derived.dark, 'dark', this.activePreset?.darkCssTokens);

    return `/* Clarity Theme Override — generated by Clarity Theme Builder */\n\n${light}\n\n${dark}`;
  }

  applyActiveTheme(theme: 'light' | 'dark') {
    this.activeTheme = theme;
    this.applyPreviewStyles();
  }

  colorToHex([h, s, l]: HslColor): string {
    return hslToHex(h, s, l);
  }

  colorToHsl([h, s, l]: HslColor): string {
    return `hsl(${h}, ${s}%, ${l}%)`;
  }

  setCurrentColor(key: keyof ThemeColors, hex: string): void {
    if (/^#[0-9a-fA-F]{6}$/.test(hex)) {
      this.colors[this.activeTheme][key].color = hexToHsl(hex);
      this.onColorChange();
    }
  }

  setDerivedOverride(field: DerivableField, hex: string): void {
    field.override = hexToHsl(hex);
    this.onDerivedChange();
  }

  ngOnInit(): void {
    console.log('ngOnInit');
    // document.querySelector('app-root')?.classList.add('layout-theme-builder');

    const style = window.getComputedStyle(document.body);
    console.log(style.getPropertyValue('--cds-alias-primary')); // #336699
    console.log(style.getPropertyValue('--cds-alias-primary-shade'));
  }

  ngAfterViewInit(): void {
    this.applyPreviewStyles();
  }

  ngOnDestroy(): void {
    console.log('ngOnDestroy');
    // document.querySelector('app-root')?.classList.remove('layout-theme-builder');
    if (this.copiedTimer) {
      clearTimeout(this.copiedTimer);
    }
  }

  applyPreset(preset: ThemePreset): void {
    this.activePreset = preset;
    this.colors.light = cloneThemeColors(preset.light);
    this.colors.dark = cloneThemeColors(preset.dark);
    this.recomputeDerived();
  }

  onColorChange(): void {
    this.activePreset = null;
    this.recomputeDerived();
  }

  toggleManual(field: keyof DerivedSet): void {
    const f = this.currentDerived[field];
    if (!f.useManual) {
      f.override = f.auto;
    }
    f.useManual = !f.useManual;
    this.applyPreviewStyles();
  }

  onDerivedChange(): void {
    this.applyPreviewStyles();
  }

  async copyCSS(): Promise<void> {
    try {
      await navigator.clipboard.writeText(this.generatedCss);
      this.copied = true;
      if (this.copiedTimer) {
        clearTimeout(this.copiedTimer);
      }
      this.copiedTimer = setTimeout(() => (this.copied = false), 2000);
    } catch {
      // clipboard not available — silently ignore
    }
  }

  applyPreviewStyles(): void {
    const el = this.previewWrapper?.nativeElement;
    if (!el) {
      return;
    }
    const c = this.colors[this.activeTheme];
    const d = this.derived[this.activeTheme];

    const hsl = (color: HslColor) => this.colorToHsl(color);
    const ev = (f: DerivableField) => hsl(effectiveValue(f));

    const vars: Record<string, string> = {
      '--cds-alias-status-info': hsl(c.primary.color),
      '--cds-alias-status-info-tint': ev(d.primaryTint),
      '--cds-alias-status-info-shade': ev(d.primaryShade),
      '--cds-alias-object-interaction-background-highlight': hsl(c.primary.color),
      '--cds-alias-object-interaction-background-selected': ev(d.primaryTint),
      '--cds-alias-object-interaction-info-hover': ev(d.primaryHover),
      '--cds-alias-object-interaction-info-click': ev(d.primaryActive),
      '--cds-alias-object-interaction-info-active': ev(d.primaryActive),
      '--cds-alias-object-interaction-info-selected': ev(d.primaryActive),
      '--cds-alias-object-interaction-info-secondary-hover': ev(d.primaryTint),
      '--cds-alias-typography-link-color': hsl(c.primary.color),
      '--cds-alias-typography-link-color-hover': ev(d.primaryHover),
      '--cds-alias-typography-info-hover': ev(d.primaryHover),
      '--cds-alias-status-success': hsl(c.success.color),
      '--cds-alias-status-success-tint': ev(d.successTint),
      '--cds-alias-status-success-shade': ev(d.successShade),
      '--cds-alias-object-interaction-success-hover': ev(d.successHover),
      '--cds-alias-object-interaction-success-click': ev(d.successActive),
      '--cds-alias-object-interaction-success-active': ev(d.successActive),
      '--cds-alias-object-interaction-success-secondary-hover': ev(d.successTint),
      '--cds-alias-typography-success-hover': ev(d.successHover),
      '--cds-alias-status-warning': hsl(c.warning.color),
      '--cds-alias-status-warning-tint': ev(d.warningTint),
      '--cds-alias-status-warning-shade': ev(d.warningShade),
      '--cds-alias-status-warning-dark': ev(d.warningActive),
      '--cds-alias-object-interaction-warning-hover': ev(d.warningHover),
      '--cds-alias-object-interaction-warning-click': ev(d.warningActive),
      '--cds-alias-object-interaction-warning-active': ev(d.warningActive),
      '--cds-alias-object-interaction-warning-secondary-hover': ev(d.warningTint),
      '--cds-alias-typography-warning-hover': ev(d.warningHover),
      '--cds-alias-status-danger': hsl(c.danger.color),
      '--cds-alias-status-danger-tint': ev(d.dangerTint),
      '--cds-alias-status-danger-shade': ev(d.dangerShade),
      '--cds-alias-status-danger-dark': ev(d.dangerActive),
      '--cds-alias-object-interaction-danger-hover': ev(d.dangerHover),
      '--cds-alias-object-interaction-danger-click': ev(d.dangerActive),
      '--cds-alias-object-interaction-danger-active': ev(d.dangerActive),
      '--cds-alias-object-interaction-danger-secondary-hover': ev(d.dangerTint),
      '--cds-alias-typography-danger-hover': ev(d.dangerHover),
      '--cds-alias-object-app-background': hsl(c.appBg.color),
      '--cds-alias-object-container-background': hsl(c.containerBg.color),
      '--cds-alias-object-overlay-background': hsl(c.containerBg.color),
      '--cds-alias-typography-color-500': hsl(c.text.color),
    };
    for (const [prop, val] of Object.entries(vars)) {
      el.style.setProperty(prop, val);
    }
    el.style.backgroundColor = hsl(c.appBg.color);
    el.style.color = hsl(c.text.color);
  }

  private recomputeDerived(): void {
    this.derived.light = buildDerivedSet(this.colors.light, this.derived.light, false);
    this.derived.dark = buildDerivedSet(this.colors.dark, this.derived.dark, true);
    this.applyPreviewStyles();
  }
}
