/*
 * Copyright (c) 2016-2026 Broadcom. All Rights Reserved.
 * The term "Broadcom" refers to Broadcom Inc. and/or its subsidiaries.
 * This software is released under MIT license.
 * The full license information can be found in LICENSE in the root directory of this project.
 */

import { Component, EventEmitter, Input, Output } from '@angular/core';

/**
 * A toggle with a label control that can be used in the
 * multi page dialog's header section.
 */
@Component({
  selector: 'appfx-toggle',
  standalone: false,
  templateUrl: 'toggle.component.html',
  styleUrls: ['toggle.component.scss'],
})
export class ToggleComponent {
  private static instanceCount = 0;

  /** Dispatched when the toggle enabled state is changed. */
  @Output() toggleStateChange = new EventEmitter<boolean>();

  /** The enabled toggle state - true or false. */
  @Input() toggleState = false;

  /**
   * The toggle control ID. If it is not specified,
   * an autogenerated ID will be set.
   */
  @Input() toggleId: string;

  /** The label/description of the toggle. */
  @Input() label: string;

  @Input() disabled: boolean;

  constructor() {
    ToggleComponent.instanceCount++;
    this.toggleId = 'toggle_' + ToggleComponent.instanceCount;
  }

  /**
   * Triggered when the toggle state has changed.
   * @param state The current state
   */
  onToggleStateChanged(state: boolean): void {
    this.toggleStateChange.emit(state);
  }
}
