/*
 * Copyright (c) 2016-2026 Broadcom. All Rights Reserved.
 * The term "Broadcom" refers to Broadcom Inc. and/or its subsidiaries.
 * This software is released under MIT license.
 * The full license information can be found in LICENSE in the root directory of this project.
 */

export const CATEGORY_ENUM_VALUES: Record<string, string> = {
  'auth.login': 'User Login',
  'auth.logout': 'User Logout',
  'auth.password_change': 'Password Changed',
  'auth.mfa_enabled': 'MFA Enabled',
  'auth.mfa_disabled': 'MFA Disabled',
  'auth.session_expired': 'Session Expired',
  'auth.account_locked': 'Account Locked',
  'auth.account_unlocked': 'Account Unlocked',
  'resource.created': 'Resource Created',
  'resource.updated': 'Resource Updated',
  'resource.deleted': 'Resource Deleted',
  'resource.archived': 'Resource Archived',
  'resource.restored': 'Resource Restored',
  'resource.exported': 'Resource Exported',
  'resource.imported': 'Resource Imported',
  'config.updated': 'Configuration Updated',
  'config.reset': 'Configuration Reset',
  'config.backup_created': 'Config Backup Created',
  'config.backup_restored': 'Config Backup Restored',
  'deploy.started': 'Deployment Started',
  'deploy.completed': 'Deployment Completed',
  'deploy.failed': 'Deployment Failed',
  'deploy.rolled_back': 'Deployment Rolled Back',
  'deploy.cancelled': 'Deployment Cancelled',
  'alert.triggered': 'Alert Triggered',
  'alert.acknowledged': 'Alert Acknowledged',
  'alert.resolved': 'Alert Resolved',
  'alert.escalated': 'Alert Escalated',
  'alert.suppressed': 'Alert Suppressed',
  'permission.granted': 'Permission Granted',
  'permission.revoked': 'Permission Revoked',
  'permission.role_assigned': 'Role Assigned',
  'permission.role_removed': 'Role Removed',
  'system.started': 'System Started',
  'system.stopped': 'System Stopped',
  'system.restarted': 'System Restarted',
  'system.health_check': 'Health Check',
  'system.maintenance_start': 'Maintenance Started',
  'system.maintenance_end': 'Maintenance Ended',
  'data.sync_started': 'Data Sync Started',
  'data.sync_completed': 'Data Sync Completed',
  'data.sync_failed': 'Data Sync Failed',
  'data.migration_started': 'Data Migration Started',
  'data.migration_completed': 'Data Migration Completed',
  'network.connected': 'Network Connected',
  'network.disconnected': 'Network Disconnected',
  'network.latency_warning': 'Network Latency Warning',
  'network.firewall_updated': 'Firewall Rules Updated',
  'storage.threshold_warning': 'Storage Threshold Warning',
  'storage.capacity_reached': 'Storage Capacity Reached',
  'storage.cleanup_completed': 'Storage Cleanup Completed',
  'audit.report_generated': 'Audit Report Generated',
  'audit.compliance_check': 'Compliance Check',
  'audit.policy_violation': 'Policy Violation Detected',
};
