/*
 * Copyright (c) 2016-2026 Broadcom. All Rights Reserved.
 * The term "Broadcom" refers to Broadcom Inc. and/or its subsidiaries.
 * This software is released under MIT license.
 * The full license information can be found in LICENSE in the root directory of this project.
 */

// Generated by scripts/generate-examples.js from examples.json. Do not edit; run `npm run examples:generate`.

import { BUTTON_EXAMPLES } from '@clr/examples/button';
import { Meta, StoryObj } from '@storybook/angular';

import { exampleStoriesDecorators, exampleStoriesParameters, exampleStory } from '../../helpers/example-story';

export default {
  title: 'Button/Examples',
  decorators: exampleStoriesDecorators,
  parameters: exampleStoriesParameters,
} satisfies Meta;

export const Solid: StoryObj = exampleStory(BUTTON_EXAMPLES.solid);

export const Outline: StoryObj = exampleStory(BUTTON_EXAMPLES.outline);

export const Flat: StoryObj = exampleStory(BUTTON_EXAMPLES.flat);

export const StatusAll: StoryObj = exampleStory(BUTTON_EXAMPLES.statusAll);

export const SizeSmall: StoryObj = exampleStory(BUTTON_EXAMPLES.sizeSmall);

export const Block: StoryObj = exampleStory(BUTTON_EXAMPLES.block);

export const Inverse: StoryObj = exampleStory(BUTTON_EXAMPLES.inverse);

export const Icon: StoryObj = exampleStory(BUTTON_EXAMPLES.icon);

export const IconSizes: StoryObj = exampleStory(BUTTON_EXAMPLES.iconSizes);
