/*
 * Copyright (c) 2016-2026 Broadcom. All Rights Reserved.
 * The term "Broadcom" refers to Broadcom Inc. and/or its subsidiaries.
 * This software is released under MIT license.
 * The full license information can be found in LICENSE in the root directory of this project.
 */

import { Color } from './color';
import { DEFAULT_OVERRIDES } from './presets';
import { CdsThemeStructure } from './types';

export function generateCSS(colorStruct: CdsThemeStructure, warningTextOverrideEnabled = true): string[] {
  const lines: string[] = ['/* Clarity Theme Override — generated by Clarity Theme Builder */'];
  const defaultOverrides = new Set<string>();

  for (const theme in colorStruct) {
    const changedGroups: { key: string; colors: Color[] }[] = [];

    for (const colorGroupKey in colorStruct[theme]) {
      const colorVariants = colorStruct[theme][colorGroupKey] as Color[];
      const changedColors = colorVariants.filter(color => !color.isOriginalColor);

      if (changedColors.length) {
        changedGroups.push({ key: colorGroupKey, colors: changedColors });
      }
    }

    if (!changedGroups.length) {
      continue;
    }

    lines.push(`\n\n[cds-theme~='${theme}'] {`);

    for (const group of changedGroups) {
      lines.push(`  /* ${group.key} */`);

      for (const color of group.colors) {
        lines.push(`  ${color.name}: ${color.hsl};`);

        // warning text override — mirrors the same condition applied live in applyPreviewStyles; light theme only
        if (warningTextOverrideEnabled && theme === 'light' && color.name === '--cds-alias-status-warning') {
          lines.push(`  --cds-alias-typography-color-black: var(--cds-alias-typography-color-100);`);
        }

        DEFAULT_OVERRIDES[color.name]?.forEach((override: string) => {
          const overrideResult = `  ${override}: var(${color.name});`;

          if (!defaultOverrides.has(overrideResult)) {
            defaultOverrides.add(overrideResult);
          }
        });
      }

      lines.push('');
    }
    lines.push(`}`);
  }

  if (lines.length === 1) {
    lines.push('\n/* NO changes */');
  }

  if (defaultOverrides.size > 0) {
    const overrideLines = ['\n\n[cds-theme] {', ...defaultOverrides.values(), '}'];

    return lines.slice(0, 1).concat(overrideLines, lines.slice(1));
  }

  return lines;
}
