/*
 * Copyright (c) 2016-2026 Broadcom. All Rights Reserved.
 * The term "Broadcom" refers to Broadcom Inc. and/or its subsidiaries.
 * This software is released under MIT license.
 * The full license information can be found in LICENSE in the root directory of this project.
 */

// Generated by scripts/generate-examples.js from examples.json. Do not edit; run `npm run examples:generate`.

import { Example } from '../example';
import { ButtonBlockExample } from './block.example';
import { ButtonFlatExample } from './flat.example';
import { ButtonIconSizesExample } from './icon-sizes.example';
import { ButtonIconExample } from './icon.example';
import { ButtonInverseExample } from './inverse.example';
import { ButtonLoadingStatesExample } from './loading-states.example';
import { ButtonLoadingExample } from './loading.example';
import { ButtonOutlineExample } from './outline.example';
import { ButtonSizeFlatNormalExample } from './size-flat-normal.example';
import { ButtonSizeFlatSmallExample } from './size-flat-small.example';
import { ButtonSizeNormalExample } from './size-normal.example';
import { ButtonSizeSmallExample } from './size-small.example';
import { ButtonSolidExample } from './solid.example';
import { ButtonStatusAllExample } from './status-all.example';
import { ButtonStatusOutlineExample } from './status-outline.example';
import { ButtonStatusSolidExample } from './status-solid.example';

export const BUTTON_EXAMPLES = {
  solid: {
    id: 'button/solid',
    title: 'Solid buttons',
    targets: ['website', 'demo', 'storybook'],
    component: ButtonSolidExample,
    showStyles: true,
    source: {
      html: '<button class="btn btn-primary">Primary</button>\n<button class="btn btn-info">Info</button>\n<button class="btn btn-success">Success</button>\n<button class="btn btn-warning">Warning</button>\n<button class="btn btn-danger">Danger</button>\n<button class="btn btn-danger" disabled>Disabled</button>\n',
      ts: "import { Component } from '@angular/core';\n\n@Component({\n  selector: 'app-example',\n  templateUrl: './example.component.html',\n})\nexport class ExampleComponent {}\n",
      hasLogic: false,
    },
  },
  outline: {
    id: 'button/outline',
    title: 'Outline buttons',
    targets: ['website', 'demo', 'storybook'],
    component: ButtonOutlineExample,
    showStyles: true,
    source: {
      html: '<button class="btn btn-outline">Regular</button>\n<button class="btn btn-success-outline">Success-Outline</button>\n<button class="btn btn-info-outline">Info</button>\n<button class="btn btn-warning-outline">Warning</button>\n<button class="btn btn-danger-outline">Danger</button>\n<button class="btn btn-outline" disabled>Disabled</button>\n',
      ts: "import { Component } from '@angular/core';\n\n@Component({\n  selector: 'app-example',\n  templateUrl: './example.component.html',\n})\nexport class ExampleComponent {}\n",
      hasLogic: false,
    },
  },
  flat: {
    id: 'button/flat',
    title: 'Flat buttons',
    targets: ['website', 'demo', 'storybook'],
    component: ButtonFlatExample,
    showStyles: true,
    source: {
      html: '<button class="btn btn-link">Regular</button>\n<button class="btn btn-link" disabled>Disabled</button>\n<button class="btn btn-sm btn-link">Regular</button>\n<button class="btn btn-sm btn-link" disabled>Disabled</button>\n',
      ts: "import { Component } from '@angular/core';\n\n@Component({\n  selector: 'app-example',\n  templateUrl: './example.component.html',\n})\nexport class ExampleComponent {}\n",
      hasLogic: false,
    },
  },
  statusOutline: {
    id: 'button/status-outline',
    title: 'Outline status buttons',
    targets: ['website', 'demo', 'storybook'],
    component: ButtonStatusOutlineExample,
    showStyles: true,
    source: {
      html: '<button class="btn btn-info-outline">Info</button>\n<button class="btn btn-success-outline">Success</button>\n<button class="btn btn-danger-outline">Danger</button>\n',
      ts: "import { Component } from '@angular/core';\n\n@Component({\n  selector: 'app-example',\n  templateUrl: './example.component.html',\n})\nexport class ExampleComponent {}\n",
      hasLogic: false,
    },
  },
  statusSolid: {
    id: 'button/status-solid',
    title: 'Solid status buttons',
    targets: ['website', 'demo', 'storybook'],
    component: ButtonStatusSolidExample,
    showStyles: true,
    source: {
      html: '<button class="btn btn-success">Success</button>\n<button class="btn btn-danger">Danger</button>\n',
      ts: "import { Component } from '@angular/core';\n\n@Component({\n  selector: 'app-example',\n  templateUrl: './example.component.html',\n})\nexport class ExampleComponent {}\n",
      hasLogic: false,
    },
  },
  statusAll: {
    id: 'button/status-all',
    title: 'All status buttons',
    targets: ['demo', 'storybook'],
    component: ButtonStatusAllExample,
    showStyles: true,
    source: {
      html: '<h4>Outline</h4>\n<button class="btn btn-primary-outline">Primary</button>\n<button class="btn btn-info-outline">Info</button>\n<button class="btn btn-success-outline">Success</button>\n<button class="btn btn-warning-outline">Warning</button>\n<button class="btn btn-danger-outline">Danger</button>\n\n<h4>Outline disabled</h4>\n<button class="btn btn-primary-outline" disabled>Primary</button>\n<button class="btn btn-info-outline" disabled>Info</button>\n<button class="btn btn-success-outline" disabled>Success</button>\n<button class="btn btn-warning-outline" disabled>Warning</button>\n<button class="btn btn-danger-outline" disabled>Danger</button>\n\n<h4>Solid</h4>\n<button class="btn btn-primary">Primary</button>\n<button class="btn btn-info">Info</button>\n<button class="btn btn-success">Success</button>\n<button class="btn btn-warning">Warning</button>\n<button class="btn btn-danger">Danger</button>\n\n<h4>Solid disabled</h4>\n<button class="btn btn-primary" disabled>Disabled Primary</button>\n<button class="btn btn-info" disabled>Disabled Info</button>\n<button class="btn btn-success" disabled>Disabled Success</button>\n<button class="btn btn-warning" disabled>Disabled Warning</button>\n<button class="btn btn-danger" disabled>Disabled Danger</button>\n\n<h4>Link</h4>\n<button class="btn btn-link-primary">Primary</button>\n<button class="btn btn-link-info">Info</button>\n<button class="btn btn-link-success">Success</button>\n<button class="btn btn-link-warning">Warning</button>\n<button class="btn btn-link-danger">Danger</button>\n\n<h4>Link disabled</h4>\n<button class="btn btn-link-primary" disabled>Disabled Primary</button>\n<button class="btn btn-link-info" disabled>Disabled Info</button>\n<button class="btn btn-link-success" disabled>Disabled Success</button>\n<button class="btn btn-link-warning" disabled>Disabled Warning</button>\n<button class="btn btn-link-danger" disabled>Disabled Danger</button>\n',
      ts: "import { Component } from '@angular/core';\n\n@Component({\n  selector: 'app-example',\n  templateUrl: './example.component.html',\n})\nexport class ExampleComponent {}\n",
      hasLogic: false,
    },
  },
  sizeNormal: {
    id: 'button/size-normal',
    title: 'Normal buttons',
    targets: ['website', 'demo', 'storybook'],
    component: ButtonSizeNormalExample,
    showStyles: true,
    source: {
      html: '<button class="btn">Regular</button>\n<button class="btn btn-primary">Primary</button>\n<button class="btn btn-success">Success</button>\n<button class="btn btn-info">Info</button>\n<button class="btn btn-warning">Warning</button>\n<button class="btn btn-danger">Danger</button>\n<button class="btn" disabled>Disabled</button>\n',
      ts: "import { Component } from '@angular/core';\n\n@Component({\n  selector: 'app-example',\n  templateUrl: './example.component.html',\n})\nexport class ExampleComponent {}\n",
      hasLogic: false,
    },
  },
  sizeSmall: {
    id: 'button/size-small',
    title: 'Small buttons',
    targets: ['website', 'demo', 'storybook'],
    component: ButtonSizeSmallExample,
    showStyles: true,
    source: {
      html: '<button class="btn btn-sm">Regular</button>\n<button class="btn btn-primary btn-sm">Primary</button>\n<button class="btn btn-success btn-sm">Success</button>\n<button class="btn btn-info btn-sm">Info</button>\n<button class="btn btn-warning btn-sm">Warning</button>\n<button class="btn btn-danger btn-sm">Danger</button>\n<button class="btn btn-sm" disabled>Disabled</button>\n',
      ts: "import { Component } from '@angular/core';\n\n@Component({\n  selector: 'app-example',\n  templateUrl: './example.component.html',\n})\nexport class ExampleComponent {}\n",
      hasLogic: false,
    },
  },
  sizeFlatNormal: {
    id: 'button/size-flat-normal',
    title: 'Normal flat buttons',
    targets: ['website', 'demo', 'storybook'],
    component: ButtonSizeFlatNormalExample,
    showStyles: true,
    source: {
      html: '<button class="btn btn-link">Flat Regular</button>\n<button class="btn btn-link" disabled>Flat Disabled</button>\n',
      ts: "import { Component } from '@angular/core';\n\n@Component({\n  selector: 'app-example',\n  templateUrl: './example.component.html',\n})\nexport class ExampleComponent {}\n",
      hasLogic: false,
    },
  },
  sizeFlatSmall: {
    id: 'button/size-flat-small',
    title: 'Small flat buttons',
    targets: ['website', 'demo', 'storybook'],
    component: ButtonSizeFlatSmallExample,
    showStyles: true,
    source: {
      html: '<button class="btn btn-link btn-sm">Flat Regular</button>\n<button class="btn btn-link btn-sm" disabled>Flat Disabled</button>\n',
      ts: "import { Component } from '@angular/core';\n\n@Component({\n  selector: 'app-example',\n  templateUrl: './example.component.html',\n})\nexport class ExampleComponent {}\n",
      hasLogic: false,
    },
  },
  block: {
    id: 'button/block',
    title: 'Block buttons',
    targets: ['website', 'demo', 'storybook'],
    component: ButtonBlockExample,
    showStyles: true,
    source: {
      html: '<button class="btn btn-primary btn-block">Primary</button>\n<button class="btn btn-success btn-block">Success</button>\n',
      ts: "import { Component } from '@angular/core';\n\n@Component({\n  selector: 'app-example',\n  templateUrl: './example.component.html',\n})\nexport class ExampleComponent {}\n",
      hasLogic: false,
    },
  },
  inverse: {
    id: 'button/inverse',
    title: 'Inverse buttons',
    targets: ['website', 'demo', 'storybook'],
    component: ButtonInverseExample,
    showStyles: false,
    source: {
      html: '<button class="btn btn-inverse">Inverse</button>\n<button class="btn btn-inverse" disabled>Disabled Inverse</button>\n',
      ts: "import { Component } from '@angular/core';\n\n@Component({\n  selector: 'app-example',\n  templateUrl: './example.component.html',\n  styleUrl: './example.component.scss',\n})\nexport class ExampleComponent {}\n",
      scss: ':host {\n  display: block;\n  background: var(--cds-global-color-construction-900);\n  padding: var(--cds-global-space-9);\n}\n',
      hasLogic: false,
    },
  },
  icon: {
    id: 'button/icon',
    title: 'Icon buttons',
    targets: ['website', 'demo', 'storybook'],
    component: ButtonIconExample,
    showStyles: true,
    source: {
      html: '<button type="button" class="btn btn-icon" aria-label="home">\n  <clr-icon shape="home"></clr-icon>\n</button>\n<button type="button" class="btn btn-icon btn-primary" aria-label="settings">\n  <clr-icon shape="cog"></clr-icon>\n</button>\n<button type="button" class="btn btn-icon btn-warning" aria-label="warning">\n  <clr-icon shape="warning-standard"></clr-icon>\n</button>\n<button type="button" class="btn btn-icon btn-danger" aria-label="error">\n  <clr-icon shape="error-standard"></clr-icon>\n</button>\n<button type="button" class="btn btn-icon btn-success" aria-label="done">\n  <clr-icon shape="check"></clr-icon>\n</button>\n<button type="button" class="btn btn-icon" disabled aria-label="home">\n  <clr-icon shape="home"></clr-icon>\n</button>\n',
      ts: "import { Component } from '@angular/core';\nimport { ClrIcon } from '@clr/angular';\n\n@Component({\n  selector: 'app-example',\n  templateUrl: './example.component.html',\n  imports: [ClrIcon],\n})\nexport class ExampleComponent {}\n",
      hasLogic: false,
    },
  },
  iconSizes: {
    id: 'button/icon-sizes',
    title: 'Icon button sizes',
    targets: ['demo', 'storybook'],
    component: ButtonIconSizesExample,
    showStyles: true,
    source: {
      html: '<h4>Normal</h4>\n<button class="btn btn-icon" aria-label="home">\n  <clr-icon shape="home"></clr-icon>\n</button>\n<button class="btn btn-primary btn-icon" aria-label="home">\n  <clr-icon shape="home"></clr-icon>\n</button>\n<button class="btn btn-success btn-icon" aria-label="home">\n  <clr-icon shape="home"></clr-icon>\n</button>\n<button class="btn btn-info btn-icon" aria-label="home">\n  <clr-icon shape="home"></clr-icon>\n</button>\n<button class="btn btn-warning btn-icon" aria-label="home">\n  <clr-icon shape="home"></clr-icon>\n</button>\n<button class="btn btn-danger btn-icon" aria-label="home">\n  <clr-icon shape="home"></clr-icon>\n</button>\n<button class="btn btn-icon" disabled aria-label="home">\n  <clr-icon shape="home"></clr-icon>\n</button>\n\n<h4>Small</h4>\n<button class="btn btn-sm btn-icon" aria-label="home">\n  <clr-icon shape="home"></clr-icon>\n</button>\n<button class="btn btn-sm btn-primary btn-icon" aria-label="home">\n  <clr-icon shape="home"></clr-icon>\n</button>\n<button class="btn btn-sm btn-success btn-icon" aria-label="home">\n  <clr-icon shape="home"></clr-icon>\n</button>\n<button class="btn btn-sm btn-info btn-icon" aria-label="home">\n  <clr-icon shape="home"></clr-icon>\n</button>\n<button class="btn btn-sm btn-warning btn-icon" aria-label="home">\n  <clr-icon shape="home"></clr-icon>\n</button>\n<button class="btn btn-sm btn-danger btn-icon" aria-label="home">\n  <clr-icon shape="home"></clr-icon>\n</button>\n<button class="btn btn-sm btn-icon" disabled aria-label="home">\n  <clr-icon shape="home"></clr-icon>\n</button>\n\n<h4>Link normal</h4>\n<button class="btn btn-link btn-icon" aria-label="home">\n  <clr-icon shape="home"></clr-icon>\n</button>\n\n<h4>Link small</h4>\n<button class="btn btn-sm btn-link btn-icon" aria-label="home">\n  <clr-icon shape="home"></clr-icon>\n</button>\n',
      ts: "import { Component } from '@angular/core';\nimport { ClrIcon } from '@clr/angular';\n\n@Component({\n  selector: 'app-example',\n  templateUrl: './example.component.html',\n  imports: [ClrIcon],\n})\nexport class ExampleComponent {}\n",
      hasLogic: false,
    },
  },
  loading: {
    id: 'button/loading',
    title: 'Loading buttons',
    targets: ['website', 'demo', 'storybook'],
    component: ButtonLoadingExample,
    showStyles: true,
    source: {
      html: '<button [clrLoading]="validateBtnState" class="btn btn-info-outline" (click)="validateDemo()">\n  Validate\n</button>\n<button\n  [clrLoading]="submitBtnState"\n  type="submit"\n  class="btn btn-success-outline"\n  (click)="submitDemo()"\n>\n  Submit\n</button>\n',
      ts: "import { Component } from '@angular/core';\nimport { ClrButtonModule, ClrLoadingModule, ClrLoadingState } from '@clr/angular';\n\n@Component({\n  selector: 'app-example',\n  templateUrl: './example.component.html',\n  imports: [ClrButtonModule, ClrLoadingModule],\n})\nexport class ExampleComponent {\n  validateBtnState: ClrLoadingState = ClrLoadingState.DEFAULT;\n  submitBtnState: ClrLoadingState = ClrLoadingState.DEFAULT;\n\n  validateDemo() {\n    this.validateBtnState = ClrLoadingState.LOADING;\n\n    // Use actual validation logic in a real application.\n    setTimeout(() => {\n      this.validateBtnState = ClrLoadingState.SUCCESS;\n    }, 1500);\n  }\n\n  submitDemo() {\n    this.submitBtnState = ClrLoadingState.LOADING;\n\n    // Use actual submit logic in a real application.\n    setTimeout(() => {\n      this.submitBtnState = ClrLoadingState.DEFAULT;\n    }, 1500);\n  }\n}\n",
      hasLogic: true,
    },
  },
  loadingStates: {
    id: 'button/loading-states',
    title: 'Loading button states',
    targets: ['demo'],
    component: ButtonLoadingStatesExample,
    showStyles: true,
    source: {
      html: '<h4>Loading buttons with disabled input</h4>\n<button\n  [clrLoading]="disabledState"\n  [disabled]="disabledStateDisabled"\n  type="submit"\n  class="btn btn-primary"\n  (click)="disabledDemo()"\n>\n  <clr-icon shape="home"></clr-icon>\n  Disable After Success\n</button>\n<button\n  [clrLoading]="enabledState"\n  [disabled]="enabledStateDisabled"\n  type="submit"\n  class="btn btn-primary"\n  (click)="enabledDemo()"\n>\n  Enable After Success\n</button>\n\n<h4>Small loading buttons</h4>\n<button [clrLoading]="validateSmState" class="btn btn-sm btn-info-outline" (click)="validateSmDemo()">\n  <clr-icon shape="home"></clr-icon>\n  Validate\n</button>\n<button\n  [clrLoading]="submitSmState"\n  type="submit"\n  class="btn btn-sm btn-success-outline"\n  (click)="submitSmDemo()"\n>\n  <clr-icon shape="home"></clr-icon>\n  Submit\n</button>\n<button\n  [clrLoading]="validateFalsyState"\n  class="btn btn-sm btn-info-outline"\n  (click)="validateFalsyDemo()"\n>\n  Validate\n</button>\n',
      ts: "import { Component } from '@angular/core';\nimport { ClrButtonModule, ClrIcon, ClrLoadingModule, ClrLoadingState } from '@clr/angular';\n\n@Component({\n  selector: 'app-example',\n  templateUrl: './example.component.html',\n  imports: [ClrButtonModule, ClrIcon, ClrLoadingModule],\n})\nexport class ExampleComponent {\n  disabledState: ClrLoadingState = ClrLoadingState.DEFAULT;\n  enabledState: ClrLoadingState = ClrLoadingState.DEFAULT;\n  disabledStateDisabled = false;\n  enabledStateDisabled = false;\n\n  validateSmState = false;\n  submitSmState: ClrLoadingState = ClrLoadingState.DEFAULT;\n  validateFalsyState: any;\n\n  disabledDemo() {\n    this.disabledState = ClrLoadingState.LOADING;\n    setTimeout(() => {\n      this.disabledState = ClrLoadingState.SUCCESS;\n      this.disabledStateDisabled = true;\n    }, 1500);\n  }\n\n  enabledDemo() {\n    this.enabledState = ClrLoadingState.LOADING;\n    setTimeout(() => {\n      this.enabledState = ClrLoadingState.SUCCESS;\n      this.enabledStateDisabled = false;\n    }, 1500);\n  }\n\n  validateSmDemo() {\n    this.validateSmState = true;\n    setTimeout(() => {\n      this.validateSmState = false;\n    }, 1500);\n  }\n\n  submitSmDemo() {\n    this.submitSmState = ClrLoadingState.LOADING;\n    setTimeout(() => {\n      this.submitSmState = ClrLoadingState.DEFAULT;\n    }, 1500);\n  }\n\n  validateFalsyDemo() {\n    this.validateFalsyState = true;\n    setTimeout(() => {\n      this.validateFalsyState = null;\n    }, 1500);\n  }\n}\n",
      hasLogic: true,
    },
  },
} satisfies Record<string, Example>;
