/*
 * Copyright (c) 2016-2025 Broadcom. All Rights Reserved.
 * The term "Broadcom" refers to Broadcom Inc. and/or its subsidiaries.
 * This software is released under MIT license.
 * The full license information can be found in LICENSE in the root directory of this project.
 */

export const names: string[] = [
  'linux-sonar',
  'windows-website',
  'unix-system',
  'ubuntu-horizon',
  'centos-network',
  'debian-core',
  'redhat-firewall',
  'fedora-database',
  'arch-data',
  'solaris-cloud',
  'macos-server',
  'docker-container',
  'kali-security',
  'openbsd-storage',
  'windows-infrastructure',
  'linux-network',
  'freebsd-virtual',
  'unix-backup',
  'centos-vault',
  'ubuntu-cluster',
  'debian-loadbalancer',
  'redhat-proxy',
  'macos-dev',
  'windows-analytics',
  'solaris-remote',
  'openbsd-fs',
  'fedora-compute',
  'arch-node',
  'kali-testbed',
  'docker-swarm',
  'linux-automation',
  'windows-logging',
  'unix-middleware',
  'ubuntu-monitor',
  'centos-caching',
  'debian-webserver',
  'redhat-api',
  'fedora-microservices',
  'macos-frontend',
  'docker-orchestration',
  'kali-penetration',
  'openbsd-replica',
  'windows-virtualbox',
  'linux-backend',
  'freebsd-loadbalancer',
  'ubuntu-firewall',
  'solaris-frontend',
  'centos-machine',
  'debian-cluster',
  'macos-workstation',
  'docker-middleware',
  'kali-defense',
  'redhat-backend',
  'windows-cache',
  'linux-monitoring',
  'unix-execution',
  'ubuntu-virtualization',
  'openbsd-edge',
  'fedora-logger',
  'debian-pipeline',
  'centos-edge',
  'arch-docker',
  'solaris-application',
  'kali-research',
  'macos-virtualmachine',
  'redhat-sandbox',
  'windows-serverless',
  'linux-backup',
  'fedora-virtual',
  'debian-scheduler',
  'openbsd-web',
  'ubuntu-streaming',
  'centos-security',
  'windows-virtualenv',
  'solaris-infrastructure',
  'docker-integration',
  'kali-forensics',
  'freebsd-systems',
];

export const states: string[] = ['Powered On', 'Powered Off'];
export const colors: string[] = [
  'Red',
  'Orange',
  'Yellow',
  'Green',
  'Blue',
  'Indigo',
  'Violet',
  'Purple',
  'Magenta',
  'Cyan',
  'Pink',
  'Brown',
  'White',
  'Gray',
  'Black',
];

export const status: string[] = ['Normal', 'Warning', 'Alert'];

export const cpus: string[] = ['1', '2', '4', '8', '16', '32'];

export const usedSpace: number[] = [
  59.97, 87.4, 17.43, 13.32, 83.57, 64.09, 43.61, 1.22, 71.1, 97.54, 73.06, 21.46, 47.19, 94.65, 6.63, 88.41, 37.23,
  73.71, 16.91, 52.5,
];
