name: Delete Stale Visual Snapshot Branches Preview

on:
  # Allow workflow to be manually run from the GitHub UI
  workflow_dispatch:
jobs:
  cleanup_visual_snapshot_branches:
    runs-on: ubuntu-latest
    steps:
      - name: Delete visual snapshot branches
        id: delete_branches
        uses: phpdocker-io/github-actions-delete-abandoned-branches@v2
        with:
          github_token: ${{ github.token }}
          last_commit_age_days: 30
          allowed_prefixes: visual-snapshot-update/pr-
          ignore_branches: main,next,beta,15.x,13.x
          dry_run: yes
      - name: Get output
        run: "echo 'Deleted branches: ${{ steps.delete_branches.outputs.deleted_branches }}'"
