# This is a daily cron job that will lock inactive issues and PRs that have been inactive for a certain number of days.
# This is to limit the amount of noise on older issues and to encourage new issues.
# This will only lock up to 50 per run.

name: 'Lock Inactive Threads'
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  lock:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/lock-threads@v3
        with:
          issue-inactive-days: '14'
          issue-comment: 'Hi there 👋, this is an automated message. To help Clarity keep track of discussions, we automatically lock closed issues after 14 days. Please look for another open issue or open a new issue with updated details and reference this one as necessary.'
          issue-lock-reason: ''
          pr-inactive-days: '14'
          pr-comment: 'Hi there 👋, this is an automated message. To help Clarity keep track of discussions, we automatically lock closed PRs after 14 days. Please look for another open issue or open a new issue with updated details and reference this one as necessary.'
          pr-lock-reason: ''
