name: PR Build
on:
  pull_request:
concurrency:
  group: pr-build-${{github.event.pull_request.number}}
  cancel-in-progress: true
jobs:
  build-storybook:
    name: Build Storybook
    timeout-minutes: 20
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci --ignore-scripts
      - name: Build Storybook
        run: npm run _build:storybook
      - name: Upload Docs Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: dist/docs/

  pr-build:
    name: PR Build
    timeout-minutes: 30
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci --ignore-scripts
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run _build:without-storybook
      - name: Test
        run: npm run test
      - name: Public Api Check
        run: npm run public-api:check
      - name: Upload Website Artifact
        uses: actions/upload-artifact@v4
        with:
          name: website
          path: dist/website/
      - name: Upload Coverage Artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/

  pr-visual-regression-test:
    name: PR Visual Regression Test
    needs: build-storybook
    timeout-minutes: 30
    # This job intentionally does not use the `ubuntu-latest` image.
    # An updated image could generate different snapshots, so we should explicitly update the image version.
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        browser: ['chromium', 'firefox']
        theme: ['light', 'dark']
        density: ['default', 'compact']
    env:
      CLARITY_VRT_BROWSER: ${{matrix.browser}}
      CLARITY_VRT_THEME: ${{matrix.theme}}
      CLARITY_VRT_DENSITY: ${{matrix.density}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci --ignore-scripts
      - name: Cache Playwright Browsers
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{matrix.browser}}-${{hashFiles('package-lock.json')}}
      - name: Install Playwright Browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps ${{matrix.browser}}
      - name: Install Playwright System Dependencies
        if: steps.playwright-cache.outputs.cache-hit == 'true'
        run: npx playwright install-deps ${{matrix.browser}}
      - name: Download Docs Artifact
        uses: actions/download-artifact@v4
        with:
          name: docs
          path: dist/docs/
      - name: Update Visual Snapshots
        run: npx playwright test --update-snapshots
      - name: Collect Changes
        id: diff
        run: |
          git add .
          git diff --cached --binary > visual-snapshot-changes-${{matrix.browser}}-${{matrix.theme}}-${{matrix.density}}.diff
      - name: Upload Changes
        uses: actions/upload-artifact@v4
        with:
          name: visual-snapshot-changes-${{matrix.browser}}-${{matrix.theme}}-${{matrix.density}}.diff
          path: visual-snapshot-changes-${{matrix.browser}}-${{matrix.theme}}-${{matrix.density}}.diff
