name: PR Visual Regression
on:
  workflow_run:
    workflows: [PR Build]
    types:
      - completed
jobs:
  pr-visual-regression:
    if: ${{github.event.workflow_run.conclusion == 'success'}}
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: haya14busa/action-workflow_run-status@v1
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
      - name: Download Docs Artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          name: docs
          path: dist/docs
          workflow: ${{github.event.workflow_run.workflow_id}}
          run_id: ${{github.event.workflow_run.id}}
      - name: Get PR Event
        id: get_pr_event
        uses: potiuk/get-workflow-origin@v1_1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          sourceRunId: ${{github.event.workflow_run.id}}
      - name: Deploy Chromatic
        timeout-minutes: 5
        env:
          CHROMATIC_PROJECT_TOKEN: ${{secrets.CHROMATIC_PROJECT_TOKEN}}
          CHROMATIC_SHA: ${{steps.get_pr_event.outputs.sourceHeadSha}}
          CHROMATIC_BRANCH: ${{steps.get_pr_event.outputs.sourceHeadBranch}}
        run: npx chromatic --storybook-build-dir ./dist/docs
