name: PR Visual Regression
on:
  workflow_run:
    workflows: [PR Build]
    types:
      - completed
jobs:
  pr-visual-regression:
    name: PR Visual Regression
    if: ${{github.event.workflow_run.conclusion == 'success'}}
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: haya14busa/action-workflow_run-status@v1
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
      - name: Download Storybook Artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          name: storybook
          path: dist/storybook
          workflow: ${{ github.event.workflow_run.workflow_id }}
          workflow_conclusion: success
      - name: Deploy Chromatic
        timeout-minutes: 5
        env:
          CHROMATIC_PROJECT_TOKEN: ${{secrets.CHROMATIC_PROJECT_TOKEN}}
        run: npx chromatic --storybook-build-dir ./dist/storybook
